# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
- openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -bespalov0928@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
  - CODECOV_TOKEN="8c40e241-dd39-4986-9ff4-fa152ab0d122"
